import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import localFont from 'next/font/local';

import Header from '@/components/Header';
import ThemeProvider from '@/components/providers/ThemeProvider';

// varibable : TailwindCSS에서 이용하기 위해 작성
const pretendard = localFont({
    src: '../fonts/PretendardVariable.ttf',
    display: 'swap',
    weight: '45 920',
    variable: '--font-pretendard',
});

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1.0"
            />
            <body className={`${pretendard.variable} font-pretendard`}>
                <ThemeProvider>
                    <Header />
                    <main>{children}</main>
                </ThemeProvider>
            </body>
        </html>
    );
}
