import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';

import Header from '@/components/HeaderDefalut';
import ThemeProvider from '@/components/providers/ThemeProvider';


// varibable : TailwindCSS에서 이용하기 위해 작성
const pretendard = localFont({
    src: '../fonts/PretendardVariable.ttf',
    display: 'swap',
    weight: '45 920',
    variable: '--font-pretendard',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
            />
            <body
                className={`${pretendard.variable} font-pretendard min-h-svh min-w-96`}
            >
                <ThemeProvider>
                    <Header />
                    <main>{children}</main>
                </ThemeProvider>
            </body>
        </html>
    );
}
